import {
	INVENTORY_ITEM_TYPE,
	INVENTORY_ITEM_ARMOR_TYPE,
	INVENTORY_ITEM_ARMOR_SUBTYPE,
} from '@/store/character_store';

export const heavyArmor = [
	// Helmets
	{
		id: 'heavy_helmet_001',
		name: 'Iron Helm',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Прочный железный шлем.',
		stats: {
			defense: 85,
			evasion: 3,
			reduceCriticalDamage: 15,
			resistAtribute: 'None',
			itemSkill: 'none',
		},
	},
	{
		id: 'heavy_helmet_002',
		name: 'Steel Protector',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Шлем из закаленной стали.',
		stats: {
			defense: 90,
			evasion: 2,
			reduceCriticalDamage: 17,
			resistAtribute: 'None',
			itemSkill: 'Fortified Mind',
		},
	},
	{
		id: 'heavy_helmet_003',
		name: 'Dragonbone Helmet',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Изготовленный из костей дракона.',
		stats: {
			defense: 95,
			evasion: 4,
			reduceCriticalDamage: 18,
			resistAtribute: 'Fire',
			itemSkill: 'Dragon’s Resolve',
		},
	},
	{
		id: 'heavy_helmet_004',
		name: 'Ancient Warhelm',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Древний шлем, переживший множество битв.',
		stats: {
			defense: 80,
			evasion: 3,
			reduceCriticalDamage: 14,
			resistAtribute: 'Earth',
			itemSkill: 'none',
		},
	},
	{
		id: 'heavy_helmet_005',
		name: 'Titan Helm',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Шлем титанов, дарующий несокрушимую защиту.',
		stats: {
			defense: 100,
			evasion: 1,
			reduceCriticalDamage: 20,
			resistAtribute: 'None',
			itemSkill: 'Titan’s Endurance',
		},
	},

	// Body Armors
	{
		id: 'heavy_body_001',
		name: 'Iron Breastplate',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Железная кираса для защиты торса.',
		stats: {
			defense: 88,
			evasion: 2,
			reduceCriticalDamage: 15,
			resistAtribute: 'None',
			itemSkill: 'none',
		},
	},
	{
		id: 'heavy_body_002',
		name: 'Steel Chestguard',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Прочная стальная броня.',
		stats: {
			defense: 93,
			evasion: 3,
			reduceCriticalDamage: 18,
			resistAtribute: 'None',
			itemSkill: 'Defensive Stance',
		},
	},
	{
		id: 'heavy_body_003',
		name: 'Dragonbone Plate',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Латы, выкованные из драконьих костей.',
		stats: {
			defense: 97,
			evasion: 2,
			reduceCriticalDamage: 19,
			resistAtribute: 'Fire',
			itemSkill: 'Dragon’s Fortitude',
		},
	},
	{
		id: 'heavy_body_004',
		name: 'Ancient Warplate',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Закаленная временем броня древних воинов.',
		stats: {
			defense: 85,
			evasion: 3,
			reduceCriticalDamage: 14,
			resistAtribute: 'Earth',
			itemSkill: 'none',
		},
	},
	{
		id: 'heavy_body_005',
		name: 'Titan Plate',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Гигантская броня титанов, не знающих страха.',
		stats: {
			defense: 100,
			evasion: 1,
			reduceCriticalDamage: 20,
			resistAtribute: 'None',
			itemSkill: 'Titan’s Might',
		},
	},

	// Boots
	{
		id: 'heavy_boots_001',
		name: 'Iron Greaves',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Железные сапоги, защищающие ноги.',
		stats: {
			defense: 75,
			evasion: 4,
			reduceCriticalDamage: 12,
			resistAtribute: 'None',
			itemSkill: 'none',
		},
	},
	{
		id: 'heavy_boots_002',
		name: 'Steel Warboots',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Тяжелые боевые сапоги.',
		stats: {
			defense: 80,
			evasion: 5,
			reduceCriticalDamage: 14,
			resistAtribute: 'None',
			itemSkill: 'Grounded Stance',
		},
	},
	{
		id: 'heavy_boots_003',
		name: 'Dragonbone Boots',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Прочные сапоги из драконьих чешуек.',
		stats: {
			defense: 85,
			evasion: 3,
			reduceCriticalDamage: 16,
			resistAtribute: 'Fire',
			itemSkill: 'Dragon’s Step',
		},
	},
	{
		id: 'heavy_boots_004',
		name: 'Ancient Warboots',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Древние сапоги с мистической защитой.',
		stats: {
			defense: 78,
			evasion: 4,
			reduceCriticalDamage: 13,
			resistAtribute: 'Earth',
			itemSkill: 'none',
		},
	},
	{
		id: 'heavy_boots_005',
		name: 'Titan Greaves',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.HEAVY,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Непробиваемые сапоги титанов.',
		stats: {
			defense: 95,
			evasion: 2,
			reduceCriticalDamage: 18,
			resistAtribute: 'None',
			itemSkill: 'Titan’s Stride',
		},
	},
];

const lightArmor = [
	// Helmets (Hoods)
	{
		id: 'light_helmet_001',
		name: "Scout's Cap",
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Легкий головной убор разведчика.',
		stats: {
			defense: 30,
			evasion: 10,
			reduceCriticalDamage: 15,
			resistAtribute: 'None',
			itemSkill: 'none',
		},
	},
	{
		id: 'light_helmet_002',
		name: 'Hunter’s Hood',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Капюшон, используемый охотниками.',
		stats: {
			defense: 40,
			evasion: 12,
			reduceCriticalDamage: 20,
			resistAtribute: 'Wind',
			itemSkill: 'Eagle Eye',
		},
	},
	{
		id: 'light_helmet_003',
		name: 'Assassin’s Mask',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Маска, скрывающая лицо убийцы.',
		stats: {
			defense: 35,
			evasion: 15,
			reduceCriticalDamage: 10,
			resistAtribute: 'Darkness',
			itemSkill: 'Shadow Step',
		},
	},
	{
		id: 'light_helmet_004',
		name: 'Ranger’s Hat',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Шляпа лесного следопыта.',
		stats: {
			defense: 50,
			evasion: 8,
			reduceCriticalDamage: 25,
			resistAtribute: 'Earth',
			itemSkill: 'Nature’s Blessing',
		},
	},
	{
		id: 'light_helmet_005',
		name: 'Shadow Veil',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Темная вуаль для скрытных воинов.',
		stats: {
			defense: 45,
			evasion: 9,
			reduceCriticalDamage: 30,
			resistAtribute: 'Darkness',
			itemSkill: 'none',
		},
	},

	// Body (Light Armor)
	{
		id: 'light_body_001',
		name: 'Scout’s Vest',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Легкий жилет разведчика.',
		stats: {
			defense: 60,
			evasion: 7,
			reduceCriticalDamage: 15,
			resistAtribute: 'None',
			itemSkill: 'none',
		},
	},
	{
		id: 'light_body_002',
		name: 'Hunter’s Coat',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Длинный плащ охотника.',
		stats: {
			defense: 75,
			evasion: 6,
			reduceCriticalDamage: 20,
			resistAtribute: 'Wind',
			itemSkill: 'Steady Aim',
		},
	},
	{
		id: 'light_body_003',
		name: 'Assassin’s Garb',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Одежда, идеально подходящая для скрытых атак.',
		stats: {
			defense: 70,
			evasion: 12,
			reduceCriticalDamage: 10,
			resistAtribute: 'Darkness',
			itemSkill: 'Silent Step',
		},
	},
	{
		id: 'light_body_004',
		name: 'Ranger’s Jacket',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Куртка, усиливающая выносливость.',
		stats: {
			defense: 85,
			evasion: 5,
			reduceCriticalDamage: 25,
			resistAtribute: 'Earth',
			itemSkill: 'Endurance',
		},
	},
	{
		id: 'light_body_005',
		name: 'Shadow Cloak',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Плащ, скрывающий владельца в тенях.',
		stats: {
			defense: 80,
			evasion: 4,
			reduceCriticalDamage: 30,
			resistAtribute: 'Darkness',
			itemSkill: 'none',
		},
	},

	// Boots
	{
		id: 'light_boots_001',
		name: 'Scout’s Shoes',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Обувь для быстрой ходьбы.',
		stats: {
			defense: 20,
			evasion: 12,
			reduceCriticalDamage: 5,
			resistAtribute: 'None',
			itemSkill: 'none',
		},
	},
	{
		id: 'light_boots_002',
		name: 'Hunter’s Boots',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Ботинки для долгих преследований.',
		stats: {
			defense: 30,
			evasion: 14,
			reduceCriticalDamage: 10,
			resistAtribute: 'Wind',
			itemSkill: 'Swift Foot',
		},
	},
	{
		id: 'light_boots_003',
		name: 'Assassin’s Treads',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Мягкая обувь для бесшумного передвижения.',
		stats: {
			defense: 25,
			evasion: 15,
			reduceCriticalDamage: 8,
			resistAtribute: 'Darkness',
			itemSkill: 'Silent Walk',
		},
	},
	{
		id: 'light_boots_004',
		name: 'Ranger’s Boots',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Усиленные ботинки следопыта.',
		stats: {
			defense: 40,
			evasion: 9,
			reduceCriticalDamage: 15,
			resistAtribute: 'Earth',
			itemSkill: 'none',
		},
	},
	{
		id: 'light_boots_005',
		name: 'Shadow Stalkers',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.LIGHT,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Обувь, позволяющая двигаться незаметно.',
		stats: {
			defense: 35,
			evasion: 10,
			reduceCriticalDamage: 20,
			resistAtribute: 'Darkness',
			itemSkill: 'Ghost Step',
		},
	},
];

const robeArmor = [
	// Helmets (Hoods)
	{
		id: 'robe_helmet_001',
		name: 'Apprentice Hood',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Простой капюшон ученика мага.',
		stats: {
			defense: 30,
			evasion: 4,
			reduceCriticalDamage: 25,
			resistAtribute: 'None',
			itemSkill: 'none',
		},
	},
	{
		id: 'robe_helmet_002',
		name: 'Mystic Hood',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Капюшон, пропитанный магией.',
		stats: {
			defense: 40,
			evasion: 5,
			reduceCriticalDamage: 30,
			resistAtribute: 'Water',
			itemSkill: 'Mana Shield',
		},
	},
	{
		id: 'robe_helmet_003',
		name: 'Sorcerer’s Veil',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Легкая вуаль, повышающая концентрацию.',
		stats: {
			defense: 35,
			evasion: 6,
			reduceCriticalDamage: 28,
			resistAtribute: 'Fire',
			itemSkill: 'none',
		},
	},
	{
		id: 'robe_helmet_004',
		name: 'Archmage Hood',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Капюшон великого мага.',
		stats: {
			defense: 50,
			evasion: 4,
			reduceCriticalDamage: 35,
			resistAtribute: 'Lightning',
			itemSkill: 'Arcane Focus',
		},
	},
	{
		id: 'robe_helmet_005',
		name: 'Dark Prophet’s Hood',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.HELMET,
		description: 'Капюшон последователя тьмы.',
		stats: {
			defense: 45,
			evasion: 3,
			reduceCriticalDamage: 40,
			resistAtribute: 'Darkness',
			itemSkill: 'Dark Aura',
		},
	},

	// Body (Robes)
	{
		id: 'robe_body_001',
		name: 'Apprentice Robe',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Одеяние новичка в магии.',
		stats: {
			defense: 50,
			evasion: 3,
			reduceCriticalDamage: 20,
			resistAtribute: 'None',
			itemSkill: 'none',
		},
	},
	{
		id: 'robe_body_002',
		name: 'Mystic Robe',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Магическое одеяние, усиливающее заклинания.',
		stats: {
			defense: 65,
			evasion: 4,
			reduceCriticalDamage: 30,
			resistAtribute: 'Water',
			itemSkill: 'Mana Boost',
		},
	},
	{
		id: 'robe_body_003',
		name: 'Sorcerer’s Mantle',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Мантия опытного чародея.',
		stats: {
			defense: 60,
			evasion: 5,
			reduceCriticalDamage: 35,
			resistAtribute: 'Fire',
			itemSkill: 'none',
		},
	},
	{
		id: 'robe_body_004',
		name: 'Archmage Robe',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Рубашка великого мага.',
		stats: {
			defense: 75,
			evasion: 3,
			reduceCriticalDamage: 40,
			resistAtribute: 'Lightning',
			itemSkill: 'Arcane Ward',
		},
	},
	{
		id: 'robe_body_005',
		name: 'Dark Prophet’s Robe',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BODY,
		description: 'Одеяние последователя темной магии.',
		stats: {
			defense: 70,
			evasion: 2,
			reduceCriticalDamage: 50,
			resistAtribute: 'Darkness',
			itemSkill: 'Shadow Embrace',
		},
	},

	// Boots
	{
		id: 'robe_boots_001',
		name: 'Apprentice Shoes',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Простая обувь ученика.',
		stats: {
			defense: 20,
			evasion: 4,
			reduceCriticalDamage: 15,
			resistAtribute: 'None',
			itemSkill: 'none',
		},
	},
	{
		id: 'robe_boots_002',
		name: 'Mystic Sandals',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Легкие сандалии для магов.',
		stats: {
			defense: 35,
			evasion: 5,
			reduceCriticalDamage: 20,
			resistAtribute: 'Water',
			itemSkill: 'Mystic Step',
		},
	},
	{
		id: 'robe_boots_003',
		name: 'Sorcerer’s Slippers',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Обувь, улучшающая концентрацию.',
		stats: {
			defense: 30,
			evasion: 6,
			reduceCriticalDamage: 25,
			resistAtribute: 'Fire',
			itemSkill: 'none',
		},
	},
	{
		id: 'robe_boots_004',
		name: 'Archmage’s Boots',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Обувь мага, парящего над землей.',
		stats: {
			defense: 45,
			evasion: 4,
			reduceCriticalDamage: 30,
			resistAtribute: 'Lightning',
			itemSkill: 'Levitate',
		},
	},
	{
		id: 'robe_boots_005',
		name: 'Dark Prophet’s Boots',
		type: INVENTORY_ITEM_TYPE.ARMOR,
		class: INVENTORY_ITEM_ARMOR_TYPE.ROBE,
		subType: INVENTORY_ITEM_ARMOR_SUBTYPE.BOOTS,
		description: 'Обувь темного жреца.',
		stats: {
			defense: 40,
			evasion: 3,
			reduceCriticalDamage: 40,
			resistAtribute: 'Darkness',
			itemSkill: 'none',
		},
	},
];

export const ARMOR = [...heavyArmor, ...lightArmor, ...robeArmor];
